### ISSUE TITLE
Get mapping on transcripts without running the protein prediction?

### ISSUE THREAD

**Issue by ifokkema** [openvar/variantFormatter#11]
The Variant Formatter has a great feature to just quickly check the variant without having it mapped to transcripts, speeding up the call a lot. However, when asking for transcript mappings, the variant's effect on protein level is also predicted. I'm assuming that is what makes the call much slower (from my measurements, 0.25s to 0.6s). It would be great if there would be a way to skip the protein prediction, but still get the mappings.

Going into implementation details; perhaps it would be good to reform the `checkonly` argument here. Options that I see (taking the freedom to use "hg19" instead of "GRCh37" for genome build and "all" instead of "None" for transcript selection);
- Add API endpoints, internally mapping to the same code to not duplicate code; for instance 
  - `/format_variant/hg19/NC_000015.9%3Ag.40699840C%3ET/refseq/all` vs
  - `/map_variant/hg19/NC_000015.9%3Ag.40699840C%3ET/refseq/all` vs 
  - `/predict_variant/hg19/NC_000015.9%3Ag.40699840C%3ET/refseq/all`.
  Feel free to totally ignore my chosen method names here.
- One argument to the same method defines what output I want; for instance 
  - `/variantformatter/hg19/NC_000015.9%3Ag.40699840C%3ET/refseq/all/format` vs 
  -  `/variantformatter/hg19/NC_000015.9%3Ag.40699840C%3ET/refseq/all/format,map` vs 
  -  `/variantformatter/hg19/NC_000015.9%3Ag.40699840C%3ET/refseq/all/format,map,predict`.
Feel free to totally ignore my chosen argument names here.

The advantage of the given examples is that you are more free to later add functionality without making things too complicated, and without breaking existing implementations. The `check_only` argument will get messy when you choose to add more arguments to support more feature on/off switches.

**Comment by PeteCausey-Freeman** [comment]
Great suggestion. Should be relatively easy to implement in principal.

I'll look into it

**Comment by PeteCausey-Freeman** [comment]
https://github.com/openvar/variantFormatter/commit/eba002ea0517e0524ae179b208d49ffc26615018 closes this issue.

**Comment by ifokkema** [comment]
Excellent, thank you! :)
